// ──────────────────────────────────────
// Product Catalog Data
// Loaded dynamically from products.json (generated by build.js / GitHub Action)
// ──────────────────────────────────────
let products = []; // populated via fetch() in initApp()

// placeholder so the const below can reference products before fetch completes
const _placeholder = [
  {
    "id": "folding-tent",
    "name_en": "Foldable Storage Tent",
    "name_am": "የሚታጠፋ ድንኩዋን",
    "category": "tents",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/K4g4gDXDhArcGxZ-SgyJJl-01ak1rQ0atyU47YYQbJQtsri0hLHYrOcabodRxU9n5HFDA_O9OMSsl-JZs9lowZwPKK3HuhJZvReFY8Csg7rnKGIQlbwNmSOGZc_e7YXoIlnh-nmLMSYjQo23j-zCLW0-eeq9wE8IAo4Js1EPbq9VvWP9feGQ6WsfQsKRmfUp4JlPIaj3K8aZyZGNrl8-ooDJWh9EXuwlxdceqzCImr9t6CKYdBqa4s9WMu9CbPHXYAS2Qm9yYWu9OJyf0AjYzoN4Gt7st5pmMFjiFMoYYc6ne4ZCzCZGe_c_ZOQOme-315UJCpgC4lcA7k6jC9ADqQ.jpg",
    "description_en": "A lightweight tent that folds flat when not in use — sturdy and easy to store between events.",
    "description_am": "ቀላል የሆነ፣ በማይፈለግበት ጊዜ አጥፍቶ ማስቀመት የሚቻል ድንኳን። ጠንካራና ለማከማቸት ምቹ።",
    "features_en": [
      "Folds flat for easy storage",
      "Durable, weather-resistant build",
      "Great for iddir gatherings, events, restaurants, and coffee shops",
      "Quick to set up and pack away"
    ],
    "features_am": [
      "ለማከማቸት ምቹ እንዲሆን ተጣጣፊ",
      "ጠንካራና የአየር ፀባይ የሚቋቋም",
      "ለእድር፣ ዝግጅቶች፣ ምግብ ቤቶች እና ካፌዎች ተስማሚ",
      "በፍጥነት የሚተከልና የሚነሳ"
    ],
    "price_type": "flat",
    "price": 49000,
    "price_display_en": "49,000 ETB",
    "price_display_am": "49,000 ብር",
    "source_post": "https://t.me/atlantictradingtent/161",
    "image_thumb": "assets/products/folding-tent-thumb.webp",
    "image_full": "assets/products/folding-tent-full.webp"
  },
  {
    "id": "handheld-light-umbrella",
    "name_en": "Handheld Umbrella with Light",
    "name_am": "የእጅ ጥላ (ማብራት ያለው)",
    "category": "umbrellas",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/W8lH_49FOq2dxI98PaRpmPt-fXWolxcXgDOpEfenLx82XTzEc_e6rC3NYxcjq7IlLc7FmSzFQRbZOE98RD6o87RJ9Pm9RDI8AoY0nzdxjE7fmlvGrq02CCM-4sUPju51NwzURSmwOiFKwd2FBK5MNSP7cNZbyDYBy6WKOgUB5hqsXYT-t9epOXGymCs64iGqaa1tP9Gz0KQH1UWp2XU1g-ajFaSPWhRetFpxzLSU3OzPnvkrrtCvLWia9aZDwGHmRqRRIalHXLdyxsCC912U0uPR8lj9qA6Isu0vL9mr74MAZGC1OTXQVO2KWWpXJgoS_uKjAfizNe6UoET21oykjA.jpg",
    "description_en": "Compact handheld umbrella with a built-in light — perfect for rainy-season evenings. Available in multiple colors, for boys and girls.",
    "description_am": "ማብራት ያለው ትንሽ የእጅ ጥላ፣ ለክረምት ምሽት ተስማሚ። በተለያዩ ቀለማት ለወንድ እና ለሴት ልጆች ይገኛል።",
    "features_en": [
      "Built-in light for visibility at night",
      "Compact, easy to carry",
      "Available in multiple colors",
      "Great for kids"
    ],
    "features_am": [
      "በሌሊት ለመታየት የሚረዳ ማብራት አለው",
      "ለመያዝ ቀላል መጠን",
      "በተለያዩ ቀለማት ይገኛል",
      "ለልጆች ተስማሚ"
    ],
    "price_type": "flat",
    "price": 1900,
    "price_display_en": "1,900 ETB",
    "price_display_am": "1,900 ብር",
    "source_post": "https://t.me/atlantictradingtent/153",
    "image_thumb": "assets/products/handheld-light-umbrella-thumb.webp",
    "image_full": "assets/products/handheld-light-umbrella-full.webp"
  },
  {
    "id": "hollyday-chair",
    "name_en": "Holiday Flexible Plastic Chair",
    "name_am": "ሆሊደይ ተለጣጣቂ የፕላስቲክ ወንበር",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/IINJG6IrviCvY9pyV43bBbJb6eyWZijz1z4iLKhRmDhy_xS9KADskKQsjzVGWY5RtzeN16FhX4yU_Ilqb9qsos8O8yyugspdd_dPReNpkKiMDKEmfFXj0kbLcf5e0kI3-7Vt2Bk6PuMs8Fe2EQfNvssRpapiCIX-jZZnhINv8sMuVou_V_yfHKCv6TkArXiJ6gbScy1vMnV6t6DOfEcTYy-FMsLL1u2kQ0Yyj9aCPqsj_PpnKwtHkrgtIg7fbGUv-Y8NjW5W2XQBw-9lhn8DiA6vtuSwVE9i9vUo7bsnDUeofflZ3vv_DnczYWLr6jXY_qtz_jAIMGee4N5X8IjAng.jpg",
    "description_en": "Lightweight, flexible plastic chair for iddir gatherings, programs, cafés, and restaurants.",
    "description_am": "ቀላል፣ ተጣጣፊ የፕላስቲክ ወንበር ለእድር፣ ለፕሮግራም፣ ለካፌዎችና ለምግብ ቤቶች ተስማሚ።",
    "features_en": [
      "Lightweight and flexible",
      "Durable everyday use",
      "Great for iddir gatherings and programs",
      "Stackable for storage"
    ],
    "features_am": [
      "ቀላልና ተጣጣፊ",
      "ለዕለት ተዕለት አገልግሎት ጠንካራ",
      "ለእድርና ለፕሮግራም ተስማሚ",
      "ለማስቀመጥ ምቹ ተደራራቢ"
    ],
    "price_type": "flat",
    "price": 1150,
    "price_display_en": "1,150 ETB",
    "price_display_am": "1,150 ብር",
    "source_post": "https://t.me/atlantictradingtent/125",
    "image_thumb": "assets/products/hollyday-chair-thumb.webp",
    "image_full": "assets/products/hollyday-chair-full.webp"
  },
  {
    "id": "plastic-duka-small",
    "name_en": "Small Plastic Stool (ዱካ)",
    "name_am": "ትንሽ የፕላስቲክ ዱካ",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/PTbvSXjHvOHuAA0Lmw7oLATL8PLlclX9MoiSeJBqgs7Ycr8iN2jgocIak6pWRJu-B202SkPc9WSqtyDkf1yEASeVkd-Rane86vPk_lDMUAC5wq8IjGivWWVyZhAD6KHizWuykqJn-ZB315jw_nMkyJVBiN_i3P0hZNXV9Onb3yCkcqoUbI9sv5VYe3Ez1CWkxHIP3wSF9AndgE4PbWplWuUsdTdAIRWCRgsXPAUuuNc95L1SS4fxQrMdIuNbyvEIjvQObIB955Ezv9FjrU1V1ISEf2riiaxhw0wcUOAkBoPGpZzZdFmMn6ea3ToSKGhzHbOSlnsp41vVi4zJcCNZQQ.jpg",
    "description_en": "A compact, budget-friendly plastic stool for cafés and coffee shops.",
    "description_am": "ትንሽ፣ ተመጣጣኝ ዋጋ ያለው የፕላስቲክ ዱካ ለካፌዎችና ለምግብ ቤቶች ተስማሚ።",
    "features_en": [
      "Compact and lightweight",
      "Budget-friendly",
      "Durable plastic build",
      "Great for cafés and coffee shops"
    ],
    "features_am": [
      "ትንሽና ቀላል",
      "ተመጣጣኝ ዋጋ",
      "ጠንካራ ፕላስቲክ",
      "ለካፌና ለቡና ቤት ተስማሚ"
    ],
    "price_type": "flat",
    "price": 450,
    "price_display_en": "450 ETB",
    "price_display_am": "450 ብር",
    "source_post": "https://t.me/atlantictradingtent/119",
    "image_thumb": "assets/products/plastic-duka-small-thumb.webp",
    "image_full": "assets/products/plastic-duka-small-full.webp"
  },
  {
    "id": "unique-duka",
    "name_en": "Unique ዱካ (Premium)",
    "name_am": "ልዩ ዱካ",
    "category": "chairs-tables",
    "tag_en": "Premium",
    "tag_am": "ልዩ ምርት",
    "image": "https://cdn4.telesco.pe/file/i1HrsUpwUFHyRBxF48fdqMJQm6GXmSpORL3qp8rP5LZJQ4BwoagVNkCKNWww6_vCY9u9zefdMTxuTg6s4a7YrskelJFekwYsDzI_fntRSKVb3rTgmJL1Pf4lRQ5XtaLMEOf5_XFEMefyA7tXRMK3xKWU4IxbhYZdu1gMZVGKlE-AkHm1UrSW9pIX-hwbQAhnmQGc2trIztGh_u1MQ_6zAIbROFlj88WFiPglt3MQbv1nfI1Mbbyb1EeUjnnmiyu7_sphzxHAMXNjVT6GpyETxFO0Xn_A9r9EHq_QfdRXDj0VmgBckczN1e9wStKDKSTmddljyojkpPoIzn0uHM8Viw.jpg",
    "description_en": "A sturdier, premium version of our plastic ዱካ — popular with coffee shops.",
    "description_am": "ከመደበኛው የበለጠ ጠንካራ የሆነ ልዩ ዱካ፣ ለካፌዎች ተወዳጅ።",
    "features_en": [
      "Premium build quality",
      "Popular with coffee shops",
      "Durable, stackable",
      "Comfortable, stable seat"
    ],
    "features_am": [
      "ልዩ ጥራት ያለው ግንባታ",
      "በካፌዎች ተወዳጅ",
      "ጠንካራና ተደራራቢ",
      "ምቹና የተረጋጋ መቀመጫ"
    ],
    "price_type": "flat",
    "price": 3900,
    "price_display_en": "3,900 ETB",
    "price_display_am": "3,900 ብር",
    "source_post": "https://t.me/atlantictradingtent/96",
    "image_thumb": "assets/products/unique-duka-thumb.webp",
    "image_full": "assets/products/unique-duka-full.webp"
  },
  {
    "id": "arm-chair",
    "name_en": "Arm Chair",
    "name_am": "የክንድ ወንበር",
    "category": "chairs-tables",
    "tag_en": "Bestseller",
    "tag_am": "ተፈላጊ",
    "image": "https://cdn4.telesco.pe/file/PV4IvEHSnkjqPGMu6UzeINN0vRE-EXhfAxk2aN0AKbMbxLFzU_ksDhqMgj-mIMHKqCY_wXedVosNUQYX8MptBFEUYOT5UUx6O7WPIWjZiXL4dibg9HMjivnPt9I02Np3rNPr-6m-2BjWgFEAPeuUiV18lhzDnl2XS71HCg1x8ekFvhz7WSUJ7bD7lHZ1uftSjo9X2SHDGu0SiCSe82K0m9t_CmTiP1X4snrj5LqNxWGct6NOjyDNjnow0x_vBPjSx3qHOvVuMfi4o6aOYodB2oFIywT5vHV33HJ54KUBGfJV4IbR-BEa0oX2vaSvdlgV7kt9A8qYbbptG12NY10xcw.jpg",
    "description_en": "Comfortable, neat plastic arm chair for cafés, restaurants, gardens, and homes.",
    "description_am": "ምቹና ንፁህ የክንድ ወንበር ለካፌዎች፣ ምግብ ቤቶች፣ የአትክልት ስፍራ እና ለቤት ተስማሚ።",
    "features_en": [
      "Comfortable armrest design",
      "Neat, quality finish",
      "Great for cafés and gardens",
      "Durable everyday use"
    ],
    "features_am": [
      "ምቹ የክንድ ንድፍ",
      "ንፁህና ጥራት ያለው",
      "ለካፌና ለአትክልት ስፍራ ተስማሚ",
      "ለዕለት ተዕለት አገልግሎት ጠንካራ"
    ],
    "price_type": "flat",
    "price": 5700,
    "price_display_en": "5,700 ETB",
    "price_display_am": "5,700 ብር",
    "source_post": "https://t.me/atlantictradingtent/88",
    "image_thumb": "assets/products/arm-chair-thumb.webp",
    "image_full": "assets/products/arm-chair-full.webp"
  },
  {
    "id": "armless-chair",
    "name_en": "Armless Chair",
    "name_am": "ያለ ክንድ ወንበር",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/PV4IvEHSnkjqPGMu6UzeINN0vRE-EXhfAxk2aN0AKbMbxLFzU_ksDhqMgj-mIMHKqCY_wXedVosNUQYX8MptBFEUYOT5UUx6O7WPIWjZiXL4dibg9HMjivnPt9I02Np3rNPr-6m-2BjWgFEAPeuUiV18lhzDnl2XS71HCg1x8ekFvhz7WSUJ7bD7lHZ1uftSjo9X2SHDGu0SiCSe82K0m9t_CmTiP1X4snrj5LqNxWGct6NOjyDNjnow0x_vBPjSx3qHOvVuMfi4o6aOYodB2oFIywT5vHV33HJ54KUBGfJV4IbR-BEa0oX2vaSvdlgV7kt9A8qYbbptG12NY10xcw.jpg",
    "description_en": "Same quality and comfort as our arm chair, without armrests — a more affordable option.",
    "description_am": "ከክንድ ወንበሩ ጋር ተመሳሳይ ጥራትና ምቾት ያለው፣ ያለ ክንድ በተመጣጣኝ ዋጋ።",
    "features_en": [
      "Comfortable, neat design",
      "More affordable option",
      "Great for cafés and restaurants",
      "Durable everyday use"
    ],
    "features_am": [
      "ምቹና ንፁህ ንድፍ",
      "ተመጣጣኝ ዋጋ",
      "ለካፌና ለምግብ ቤት ተስማሚ",
      "ጠንካራ"
    ],
    "price_type": "flat",
    "price": 5200,
    "price_display_en": "5,200 ETB",
    "price_display_am": "5,200 ብር",
    "source_post": "https://t.me/atlantictradingtent/88",
    "image_thumb": "assets/products/armless-chair-thumb.webp",
    "image_full": "assets/products/armless-chair-full.webp"
  },
  {
    "id": "stainless-dustbin",
    "name_en": "Stainless Steel Dustbin",
    "name_am": "ስቴይንለስ ስቲል የቆሻሻ መጣያ",
    "category": "bins",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/WFqVwAc7asv8cewbfAkybECTAcrYNj6HBof61pKUS23EmiNtPUoBZy9ps1ldx37-08FGB1mz_SUExkebtXiCzJZzKYp33gDetVhnh2IyjUhfGhPyc5x1LG7SAxPmL-Qv0yAL7IC7Wu6nspKgjNN4Awmajt74nLOo5gCVmLl_ACOMCL5YiDJYJKgClJklIfGf0gBDTZ553YMu99iZrluOvXS2NWg8wGOU-pcRUKMB45S2HO9sWlI2qvIMgDq7lEUxgY7jYdK7s-XWW7lzkyaQ3H5TNHLqTIIYbfzWYc5trf2ogpX3lU1p9NwNFoC62p2RhHwapDI8QlCCuuU_SKwZhw.jpg",
    "description_en": "Sleek stainless steel dustbins for hotels, offices, and upscale spaces — including an ashtray-bin option.",
    "description_am": "ውብ የስቴይንለስ ስቲል የቆሻሻ መጣያዎች ለሆቴሎችና ለቢሮዎች፣ የሲጋራ አመድ ማስቀመጫም ይገኛል።",
    "features_en": [
      "Sleek stainless steel finish",
      "Multiple sizes including ashtray bin",
      "Ideal for hotels and offices",
      "Easy to clean"
    ],
    "features_am": [
      "ውብ የስቴይንለስ ስቲል ገጽታ",
      "የተለያዩ መጠኖች የሲጋራ ማስቀመጫንም ጨምሮ",
      "ለሆቴሎችና ለቢሮዎች ተስማሚ",
      "ለማጽዳት ቀላል"
    ],
    "price_type": "tiered",
    "price_display_en": "From 2,600 ETB",
    "price_display_am": "ከ 2,600 ብር ጀምሮ",
    "price_tiers": [
      {
        "size": "5L",
        "price": 2600
      },
      {
        "size": "7L",
        "price": 3500
      },
      {
        "size": "12L",
        "price": 3900
      },
      {
        "size": "30L (Ashtray)",
        "price": 7900
      }
    ],
    "source_post": "https://t.me/atlantictradingtent/55",
    "image_thumb": "assets/products/stainless-dustbin-thumb.webp",
    "image_full": "assets/products/stainless-dustbin-full.webp"
  },
  {
    "id": "mop-bucket-wringer",
    "name_en": "Dual Mop Bucket & Wringer",
    "name_am": "ድርብ የመወልወያ መጭመቅያ",
    "category": "plastics",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/MocB-BfQWmHpRjVi_QGfH3WxdjIlf7O6SVxy0S6jqoiQHhketZORe2wcdXHkf1keLXToyYHl1-X1xweHbNJ5MKyJ7IGtqjXfyowWEIb8K1XHDG48BIp8OwF7E9DWhcWw7xWiRTAW9g-1qsnbFoWVyvienyn2nK_mHvbtxxTvmlK0Z05bujAGuxdscF_SWFmv0k8AZg174nSjdfj5WLwEp2_lDfcOTrdB-pgQ7KL6IivO5YPeLmt9ERdSmTfvPhuSfo9mh4wHLVULuUfpp2Wx5LDQfWpZN9zAo6IqMlsUUiwaVYV7lawBH8rrwK-EQj0v8WEO52S2Nto9DLRXrzDDnA.jpg",
    "description_en": "Heavy-duty dual mop bucket with wringer, built for hotels, hospitals, schools, and offices.",
    "description_am": "ጠንካራ ድርብ የመወልወያ መጭመቅያ ለሆቴሎች፣ ሆስፒታሎች፣ ትምህርት ቤቶች እና ቢሮዎች።",
    "features_en": [
      "Dual-bucket wringer system",
      "Heavy-duty commercial build",
      "Ideal for hotels, hospitals, schools",
      "Easy to maneuver"
    ],
    "features_am": [
      "ድርብ የመወልወያ ሲስተም",
      "ጠንካራ የንግድ ደረጃ ግንባታ",
      "ለሆቴል፣ ሆስፒታልና ትምህርት ቤት ተስማሚ",
      "በቀላሉ የሚንቀሳቀስ"
    ],
    "price_type": "flat",
    "price": 18000,
    "price_display_en": "18,000 ETB",
    "price_display_am": "18,000 ብር",
    "source_post": "https://t.me/atlantictradingtent/70",
    "image_thumb": "assets/products/mop-bucket-wringer-thumb.webp",
    "image_full": "assets/products/mop-bucket-wringer-full.webp"
  },
  {
    "id": "standalone-glass-table",
    "name_en": "Glass-Top Table",
    "name_am": "የመስታወት ጠረጴዛ",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/CEnF73TkPberFLG88KmFWGROwO55--bOhtMFkGbn8Po7MkOf1MI5axa-XLUhdHvtB-y0dgJUCKHc2Ba6JtID-6rxmoacjh8syXC8KzVjxbvjmf5cN6GeYu0GwACoLXGkawPnxO0keGM5OZoW0ZyjKMFKpysq5KiuWtBr64qXGCzt1pNpC8zmp28BW6uUJPg1KKyeDDN0evPAP_OGtne-Cu-HSicFrtncvkbAlzmN0TlegjVKwAQRzsB14NlRORan5wu5V5qvNArRH21xon6qDwaF0UzEpsCxn0uqmebRyyda1MqOcjEDf5XozkBk8LJM5T1XoUl2WJ5NKLwwb4zKeA.jpg",
    "description_en": "Clean-finish table with a glass top, sold separately from chair sets.",
    "description_am": "የመስታወት ላይ ገጽታ ያለው ንፁህ ጠረጴዛ፣ ለብቻው ይሸጣል።",
    "features_en": [
      "Clean glass-top finish",
      "Sold separately from chairs",
      "Sturdy frame",
      "Easy to wipe clean"
    ],
    "features_am": [
      "ንፁህ የመስታወት ገጽታ",
      "ለብቻው የሚሸጥ",
      "ጠንካራ ፍሬም",
      "በቀላሉ የሚጸዳ"
    ],
    "price_type": "flat",
    "price": 15000,
    "price_display_en": "15,000 ETB",
    "price_display_am": "15,000 ብር",
    "source_post": "https://t.me/atlantictradingtent/50",
    "image_thumb": "assets/products/standalone-glass-table-thumb.webp",
    "image_full": "assets/products/standalone-glass-table-full.webp"
  },
  {
    "id": "3x3m-lit-umbrella-powerbank",
    "name_en": "3×3m Lit Shade Umbrella with Power Bank",
    "name_am": "3x3 ባለ ማብራት ጥላ ከኃይል ባንክ ጋር",
    "category": "umbrellas",
    "tag_en": "Premium",
    "tag_am": "ልዩ ምርት",
    "image": "https://cdn4.telesco.pe/file/tOWG1rho9zYX5tU0mNquEWEmAN6xIogF9pMahqisE_mNJre4YdJuu1D1nnMgp9OfmUZ2Ev1G6WmHN0q-sSTON-qobp4vgNETrsxc0Z264v0_-H6-h4GNC1dwgXDcVnSlBxmIdcYcS8IK45Gze8N6tr3ZrhPoCu3Y-UDmiEnWlAbLYbhYS8UKUTf79YLlNyHIThFco-kICfh073k56P_ellIt-QgZD_SCZc71332B5_U-lWnfOkL2_i5wXSAoTyZrUxp2SKWDyQAhve2JOP3EFE1lSL1WMAfIrKcr3W-U61m3Kk-mPXRRGNO76ZMgYMWp1HBgjcxouc47SSu8IR0pvw.jpg",
    "description_en": "360° rotating shade umbrella with a built-in light and power bank to keep it running after dark. Water-fillable base for wind resistance.",
    "description_am": "360 ዲግሪ የሚዞር፣ ማብራት እና ኃይል ባንክ ያለው ጥላ። ነፋስ እንዲቋቋም በውሃ የሚሞላ ቤዝ ያለው።",
    "features_en": [
      "360° rotating cantilever system",
      "Built-in light + power bank for evening use",
      "Water-fillable base for wind resistance",
      "Great for cafés, restaurants, and cars"
    ],
    "features_am": [
      "360 ዲግሪ የሚዞር",
      "ማብራትና ኃይል ባንክ ላመሻት አገልግሎት",
      "ነፋስ እንዲቋቋም የውሃ ቤዝ",
      "ለካፌ፣ ምግብ ቤትና መኪና ተስማሚ"
    ],
    "price_type": "flat",
    "price": 110000,
    "price_display_en": "110,000 ETB",
    "price_display_am": "110,000 ብር",
    "source_post": "https://t.me/atlantictradingtent/164",
    "image_thumb": "assets/products/3x3m-lit-umbrella-powerbank-thumb.webp",
    "image_full": "assets/products/3x3m-lit-umbrella-powerbank-full.webp"
  },
  {
    "id": "gojo-shade",
    "name_en": "Gojo-Style Hut Shade",
    "name_am": "ጐጆ ጥላ",
    "category": "umbrellas",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/D7TALxP_ZShWhpjblowZ52WLSB0t_HgqZ8gMJ12qQEimaPc7mmD9SNB594_FSpe_ONl8bu9lWtpE55CODQLrgxmBkg9iN8tcASHvs1MBYl4AfVB5H7z4qQoWk7XW8fyYR6Je41bv0zueSu0KRzgeVPOZqr_nK-6btzcv05ak61D36g0braqlyWB5kLj64diReTVnwnAJf38G1cziuZNnZT27mLEsa7KG1MQF9aQ-Q_hnQaSK09t_rDdYptDM0FSDnkNZDOfG3d7YL41oUsTl66GTbop2OQwlooxyci27ceqRZXQEhYn4LEskjQ_Y2rf59IzymDiQ7d12pjqhn2L0Mw.jpg",
    "description_en": "Hut-shaped outdoor shade with a wind vent opening — for cafés, restaurants, gardens, and sun cover. Stand sold separately (+1,500 ETB).",
    "description_am": "ንፋስ ማስገቢያ ያለው ጐጆ ቅርፅ ጥላ — ለካፌ፣ ምግብ ቤትና የአትክልት ስፍራ ተስማሚ። መቆሚያ ለብቻ ይሸጣል (+1,500 ብር)።",
    "features_en": [
      "Hut-style canopy with wind vent",
      "Sun and weather cover",
      "Great for cafés, restaurants, gardens",
      "Stand sold separately (+1,500 ETB)"
    ],
    "features_am": [
      "ንፋስ ማስገቢያ ያለው የጐጆ ቅርፅ",
      "ፀሐይና የአየር ፀባይ መከላከያ",
      "ለካፌ፣ ምግብ ቤትና አትክልት ስፍራ ተስማሚ",
      "መቆሚያ ለብቻ ይሸጣል (+1,500 ብር)"
    ],
    "price_type": "tiered",
    "price_display_en": "From 7,500 ETB (+1,500 stand)",
    "price_display_am": "ከ 7,500 ብር ጀምሮ (+1,500 መቆምያ)",
    "price_tiers": [
      {
        "size": "2.5×2.5m",
        "price": 7500
      },
      {
        "size": "3×3m",
        "price": 9500
      }
    ],
    "source_post": "https://t.me/atlantictradingtent/84",
    "image_thumb": "assets/products/gojo-shade-thumb.webp",
    "image_full": "assets/products/gojo-shade-full.webp"
  },
  {
    "id": "double-layer-shade",
    "name_en": "Double-Layer Shade",
    "name_am": "ድርብ ጥላ",
    "category": "umbrellas",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/PXCSyKy-qkkDRLxXy8hG1gjI4fzo6MWBoM3EO5YPYgJT5ZzlqP9MhdIyjkRbWRct_69o9oqJORqeyyRzrpze4UCBzYhaXXzqQRrKp3u_IK7McAJMBtKFn6YzO99oN4Q2z1yMVDP0MsCkYfRc8IyHIb5aCVDKZeEQmLO0SGOW9bJWYYYSS3xvXcXpgi_SErmkCMgAq2MDy9J6o9qxNTTWQT7_aHa3Y2psNrozXxZLS3LpoUDWYtQgOSEm0tGzAb5x_VyYh1eXebq-2GYoFz0Ocx7JB-JuwejzEO66h-CPux-igJLcnlCx6tOoD_kofcIXGvEQOYuzXuWC3khcNKnc2g.jpg",
    "description_en": "Double-layer, table-mountable outdoor shade — for cafés, restaurants, gardens, and sun cover. Stand sold separately (+1,500 ETB).",
    "description_am": "ጠረጴዛ ላይ የሚተከል ድርብ ጥላ — ለካፌ፣ ምግብ ቤትና የአትክልት ስፍራ ተስማሚ። መቆሚያ ለብቻ ይሸጣል (+1,500 ብር)።",
    "features_en": [
      "Double-layer canopy",
      "Table-mountable design",
      "Great for cafés, restaurants, gardens",
      "Stand sold separately (+1,500 ETB)"
    ],
    "features_am": [
      "ድርብ ሽፋን ያለው",
      "ጠረጴዛ ላይ የሚተከል ንድፍ",
      "ለካፌ፣ ምግብ ቤትና አትክልት ስፍራ ተስማሚ",
      "መቆሚያ ለብቻ ይሸጣል (+1,500 ብር)"
    ],
    "price_type": "tiered",
    "price_display_en": "From 7,000 ETB (+1,500 stand)",
    "price_display_am": "ከ 7,000 ብር ጀምሮ (+1,500 መቆምያ)",
    "price_tiers": [
      {
        "size": "2.6×2.6m",
        "price": 7000
      },
      {
        "size": "3×3m",
        "price": 8000
      }
    ],
    "source_post": "https://t.me/atlantictradingtent/73",
    "image_thumb": "assets/products/double-layer-shade-thumb.webp",
    "image_full": "assets/products/double-layer-shade-full.webp"
  },
  {
    "id": "table-set-glass",
    "name_en": "4-Chair Set with Glass Table",
    "name_am": "4 ወንበር ከመስታወት ጠረጴዛ ጋር",
    "category": "chairs-tables",
    "tag_en": "Bestseller",
    "tag_am": "ተፈላጊ",
    "image": "https://cdn4.telesco.pe/file/KgqfsCn95qvXspGtnxdDcLytUGWF4Io_FA7ohwf50dM6t4rfdJOvysnuWsGjy4uvv-WmrkpVNhHXNRF4d2qaYEVr7rhk4eUsXVlgsitp3bu2iGyBydvUgVDtIS_y4_dMFcdXAM6jlGPOEv3_H3jKsiOth7XA01u-5CydudBq1MP_YF62WUXRwk8PBVvasFcwn0K9ujvQdwlpvKzl5Vnr9mknrxCLKRhxtUJD6HtNT3C9xZjPVmQKnic2YD5GB-cPLBsOZW4MGBzafXbsHZvMSl6trs1JzCFZDJv_qgNwCWcOITmCkp2A779tv99cX0oPnvSA0HRgL0PpDS9oNVJ8KQ.jpg",
    "description_en": "Complete outdoor seating set — 4 chairs with a glass-top table. Ideal for cafés, restaurants, and gardens.",
    "description_am": "ሙሉ የውጪ መቀመጫ ስብስብ — 4 ወንበር ከመስታወት ጠረጴዛ ጋር። ለካፌ፣ ምግብ ቤትና የአትክልት ስፍራ ተስማሚ።",
    "features_en": [
      "Set of 4 matching chairs",
      "Glass-top table included",
      "Great for cafés, restaurants, gardens",
      "Weatherproof, easy to clean"
    ],
    "features_am": [
      "4 ተመሳሳይ ወንበሮች",
      "የመስታወት ጠረጴዛ ያካትታል",
      "ለካፌ፣ ምግብ ቤትና አትክልት ስፍራ ተስማሚ",
      "የአየር ፀባይ የሚቋቋምና ለማጽዳት ቀላል"
    ],
    "price_type": "flat",
    "price": 60000,
    "price_display_en": "60,000 ETB",
    "price_display_am": "60,000 ብር",
    "source_post": "https://t.me/atlantictradingtent/159",
    "image_thumb": "assets/products/table-set-glass-thumb.webp",
    "image_full": "assets/products/table-set-glass-full.webp"
  },
  {
    "id": "table-set-70x70-glass",
    "name_en": "4-Chair Set with 70×70 Black Glass Table",
    "name_am": "4 ወንበር ከ70x70 ጥቁር መስታወት ጠረጴዛ ጋር",
    "category": "chairs-tables",
    "tag_en": "Bestseller",
    "tag_am": "ተፈላጊ",
    "image": "https://cdn4.telesco.pe/file/cT_okCWW5f7kPeMwXhIqxB9TOpZ7oK1Qo0nEBrPW23O87FA_3Nhj9HQUyJAoj7oQO1De0jclaw-ZC63n3Xq-W_qO_kvyaQuDyO5nURvddy94PBOmP4jvfq_p6DzRs3C0bdcq7fcv5MoEboDvO2YZVEwJC6TWcw5RYUFffJr8IH0rPmi0911EZYX-9jvapozleL8UeMaHvDjI-ovbDIMOxfYo2aAEUinWISm7_Q92cwMzqUgN--_H57qsACq8nLGlbk5aPer68hpGEQ7iuQl8xR84ODRo2TZDtnTkQV4ZMDekgsR9krQGEC7KyY6QVHMz7EEJa5qMK6nZtl9E6huZ3w.jpg",
    "description_en": "4-chair seating set with a 70×70cm black glass table — a compact option for cafés and restaurants.",
    "description_am": "4 ወንበር ከ70x70 ሴ.ሜ ጥቁር መስታወት ጠረጴዛ ጋር — ለካፌና ለምግብ ቤት ምቹ የሆነ አነስተኛ ስብስብ።",
    "features_en": [
      "Set of 4 chairs",
      "70×70cm black glass table",
      "Compact footprint",
      "Weatherproof, easy to clean"
    ],
    "features_am": [
      "4 ወንበሮች",
      "70x70 ሴ.ሜ ጥቁር መስታወት ጠረጴዛ",
      "አነስተኛ ቦታ የሚይዝ",
      "የአየር ፀባይ የሚቋቋምና ለማጽዳት ቀላል"
    ],
    "price_type": "flat",
    "price": 25900,
    "price_display_en": "25,900 ETB",
    "price_display_am": "25,900 ብር",
    "source_post": "https://t.me/atlantictradingtent/112",
    "image_thumb": "assets/products/table-set-70x70-glass-thumb.webp",
    "image_full": "assets/products/table-set-70x70-glass-full.webp"
  },
  {
    "id": "table-set-plastic",
    "name_en": "4-Chair Set with Plastic Table",
    "name_am": "4 ወንበር ከፕላስቲክ ጠረጴዛ ጋር",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/cT_okCWW5f7kPeMwXhIqxB9TOpZ7oK1Qo0nEBrPW23O87FA_3Nhj9HQUyJAoj7oQO1De0jclaw-ZC63n3Xq-W_qO_kvyaQuDyO5nURvddy94PBOmP4jvfq_p6DzRs3C0bdcq7fcv5MoEboDvO2YZVEwJC6TWcw5RYUFffJr8IH0rPmi0911EZYX-9jvapozleL8UeMaHvDjI-ovbDIMOxfYo2aAEUinWISm7_Q92cwMzqUgN--_H57qsACq8nLGlbk5aPer68hpGEQ7iuQl8xR84ODRo2TZDtnTkQV4ZMDekgsR9krQGEC7KyY6QVHMz7EEJa5qMK6nZtl9E6huZ3w.jpg",
    "description_en": "Budget-friendly 4-chair set with a durable plastic table — great value for cafés and gardens.",
    "description_am": "ተመጣጣኝ ዋጋ ያለው 4 ወንበር ከጠንካራ ፕላስቲክ ጠረጴዛ ጋር — ለካፌና ለአትክልት ስፍራ ምርጥ።",
    "features_en": [
      "Set of 4 chairs",
      "Durable plastic table",
      "Budget-friendly",
      "Weatherproof"
    ],
    "features_am": [
      "4 ወንበሮች",
      "ጠንካራ ፕላስቲክ ጠረጴዛ",
      "ተመጣጣኝ ዋጋ",
      "የአየር ፀባይ የሚቋቋም"
    ],
    "price_type": "flat",
    "price": 15800,
    "price_display_en": "15,800 ETB",
    "price_display_am": "15,800 ብር",
    "source_post": "https://t.me/atlantictradingtent/112",
    "image_thumb": "assets/products/table-set-plastic-thumb.webp",
    "image_full": "assets/products/table-set-plastic-full.webp"
  },
  {
    "id": "table-set-mdf",
    "name_en": "4-Chair Set with MDF Table",
    "name_am": "4 ወንበር ከMDF ጠረጴዛ ጋር",
    "category": "chairs-tables",
    "tag_en": "New",
    "tag_am": "አዲስ",
    "image": "https://cdn4.telesco.pe/file/VJYhWKoz26LeBzj2pclm--gfDn7vdX8-0dnhjvgK6iFjdqP6oB2gRJhJCdtV8JnL67biG3_706SsLFQsp2r0bQ_f36rlk8OoGyCkDVXTa0vbq3ABVEehGuU6dIMxgrfp4fAD9GQkXoC1QTGzWPCbAXCNO02mMvLlibcGPJNdcbiA66Odq-8g8dhpLkc8eSp19KytJvOWFwTJFc-WK8zlEWZsGrsLwbbQpveJH-EVt3u6SSQSTl4zvc-YjWGbAwiOg4iJ_YOl0Q31to9vVH5WPdds3IonvgePh5TDVLSGvoyLKWMq9fPehst9cf3BFjU4FwCSdaHGBLzrvm9_FUC-mA.jpg",
    "description_en": "4-chair set with a solid MDF wood table — a sturdier, indoor-friendly alternative.",
    "description_am": "4 ወንበር ከጠንካራ MDF እንጨት ጠረጴዛ ጋር — ለቤት ውስጥም ተስማሚ ጠንካራ አማራጭ።",
    "features_en": [
      "Set of 4 chairs",
      "Solid MDF wood table",
      "Sturdy build",
      "Suitable indoors or outdoors"
    ],
    "features_am": [
      "4 ወንበሮች",
      "ጠንካራ MDF እንጨት ጠረጴዛ",
      "ጠንካራ ግንባታ",
      "ለቤት ውስጥም ለውጪም ተስማሚ"
    ],
    "price_type": "flat",
    "price": 17500,
    "price_display_en": "17,500 ETB",
    "price_display_am": "17,500 ብር",
    "source_post": "https://t.me/atlantictradingtent/28",
    "image_thumb": "assets/products/table-set-mdf-thumb.webp",
    "image_full": "assets/products/table-set-mdf-full.webp"
  },
  {
    "id": "zufan-bundle",
    "name_en": "Zufan Set — Chairs, Table & Umbrella Bundle",
    "name_am": "ዙፋን ስብስብ — ወንበር፣ ጠረጴዛና ጥላ",
    "category": "chairs-tables",
    "tag_en": "Bundle Discount",
    "tag_am": "የቅናሽ ስብስብ",
    "image": "https://cdn4.telesco.pe/file/QVTTVvXZ_kpGStwNGrNcS4WNN0Istye8vdCO9MldvteBTky5q5hOEevNMPPdWYnfhlnAt8-Xk6K1zZ3tYwR0sMHFbg7LVWgH7DAz-MjtIGGhaEVxnHzEIoj2G35FJL4vRLiy9RQ-QsZFS4GeAhZFjkZFK7S85xmX14_szLksvGBvUo7GZB_hPgxJEzIu98UjV_KX9jdow1N5Tahar_ioy2x5kYflC8eGZZnkYV_WgLlwGIyDcNahSvGxDtTm0q_kuFcQlWRXm2e0OIuFdEzG8TBtGjsIynpNqn10zp6JXAoGFSHAefMQemcdZ4QvrsuVFQtD3czzw6q3BPBu0Fstfw.jpg",
    "description_en": "Full outdoor set: 4 chairs, a glass table, and your choice of umbrella. Discount available when you take the full bundle.",
    "description_am": "ሙሉ የውጪ ስብስብ፦ 4 ወንበር፣ የመስታወት ጠረጴዛ እና የመረጡት ጥላ። ሙሉ ስብስቡን ለሚወስዱ ቅናሽ አለ።",
    "features_en": [
      "4 chairs + glass table + 1 umbrella",
      "Choice of lit or unlit umbrella, square or round",
      "Discount when purchasing the full bundle",
      "Great for cafés, restaurants, gardens"
    ],
    "features_am": [
      "4 ወንበር + መስታወት ጠረጴዛ + 1 ጥላ",
      "ማብራት ያለው ወይም የሌለው፣ ካሬ ወይም ክብ ጥላ መምረጥ ይቻላል",
      "ሙሉ ስብስቡን ለሚወስዱ ቅናሽ",
      "ለካፌ፣ ምግብ ቤትና አትክልት ስፍራ ተስማሚ"
    ],
    "price_type": "tiered",
    "price_display_en": "From 65,000 ETB",
    "price_display_am": "ከ 65,000 ብር ጀምሮ",
    "price_tiers": [
      {
        "size": "Chairs + table only",
        "price": 79000
      },
      {
        "size": "+ Round umbrella (no light)",
        "price": 65000
      },
      {
        "size": "+ Square umbrella (no light)",
        "price": 75000
      },
      {
        "size": "+ Lit umbrella",
        "price": 90000
      }
    ],
    "source_post": "https://t.me/atlantictradingtent/149",
    "image_thumb": "assets/products/zufan-bundle-thumb.webp",
    "image_full": "assets/products/zufan-bundle-full.webp"
  }
]; // end _placeholder — remove this entire block once migration is done

// ──────────────────────────────────────
// Categories
// ──────────────────────────────────────
const categories = [
  { id: "all",           name_en: "All Products",    name_am: "ሁሉም ምርቶች" },
  { id: "bins",          name_en: "Garbage Cans",    name_am: "የቆሻሻ መጣያ",    image: "assets/products/stainless-dustbin-thumb.webp" },
  { id: "umbrellas",     name_en: "Shade Umbrellas", name_am: "የፀሐይ ጥላዎች",   image: "assets/products/double-layer-shade-thumb.webp" },
  { id: "chairs-tables", name_en: "Chairs & Tables", name_am: "ወንበርና ጠረጴዛ",  image: "assets/products/table-set-glass-thumb.webp" },
  { id: "tents",         name_en: "Tents & Gazebos", name_am: "ድንኳኖች",        image: "assets/products/folding-tent-thumb.webp" },
  { id: "plastics",      name_en: "Plastic Goods",   name_am: "የፕላስቲክ ዕቃዎች", image: "assets/products/plastic-duka-small-thumb.webp" }
];

// ──────────────────────────────────────
// Translation Dictionary
// ──────────────────────────────────────
const dictionary = {
  en: {
    "hero-badge":         "TRUSTED SUPPLIER",
    "hero-title-main":    "ATLANTIC TRADING",
    "hero-title-sub":     "Quality Outdoor & Plastic Gear",
    "hero-subtitle":      "For your business & home. Premium shade umbrellas, tents, plastic chairs, and garbage cans in Addis Ababa.",
    "hero-cta":           "Browse Catalog",
    "hero-tg-cta":        "Order on Telegram",
    "call-now":           "Call to Order",
    "section-categories": "Browse Categories",
    "section-catalog":    "Our Product Catalog",
    "search-placeholder": "Search products...",
    "pdp-key-features":   "Key Specifications",
    "pdp-pricing-table":  "Size & Price Tiers",
    "th-size":            "Capacity / Size",
    "th-price":           "Price (ETB)",
    "order-telegram":     "Order via Telegram",
    "order-call":         "Call to Order",
    "footer-contact-us":  "Get in Touch",
    "footer-location":    "Addis Ababa, Ethiopia",
    "footer-follow-us":   "Follow Us",
    "footer-rights":      "All Rights Reserved.",
    "sticky-tg":          "Order on Telegram",
    "sticky-call":        "Call",
    "price-from":         "From",
    "nav-join-tg":        "Join Channel",
    "no-results":         "No products found. Try a different search."
  },
  am: {
    "hero-badge":         "ታማኝ አቅራቢ",
    "hero-title-main":    "አትላንቲክ ትሬዲንግ",
    "hero-title-sub":     "ጥራት ያላቸው የውጪና ፕላስቲክ ዕቃዎች",
    "hero-subtitle":      "ለቤትዎ እና ለንግድዎ። ምርጥ የፀሐይ ጥላዎች፣ ድንኳኖች፣ የፕላስቲክ ወንበሮች እና የቆሻሻ መጣያ ባልዲዎች በአዲስ አበባ።",
    "hero-cta":           "ካታሎግ ይመልከቱ",
    "hero-tg-cta":        "በቴሌግራም እዘዝ",
    "call-now":           "ደውለው ይዘዙ",
    "section-categories": "ምድቦች",
    "section-catalog":    "የምርት ዝርዝር",
    "search-placeholder": "ዕቃዎችን ይፈልጉ...",
    "pdp-key-features":   "ዋና መለያዎች",
    "pdp-pricing-table":  "የመጠን እና የዋጋ ዝርዝር",
    "th-size":            "መጠን / ሊትር",
    "th-price":           "ዋጋ (ብር)",
    "order-telegram":     "በቴሌግራም እዘዝ",
    "order-call":         "ደውለው ለማዘዝ",
    "footer-contact-us":  "ያግኙን",
    "footer-location":    "አዲስ አበባ፣ ኢትዮጵያ",
    "footer-follow-us":   "ይከተሉን",
    "footer-rights":      "መብቱ በህግ የተጠበቀ ነው።",
    "sticky-tg":          "በቴሌግራም እዘዝ",
    "sticky-call":        "ደውል",
    "price-from":         "ከ",
    "nav-join-tg":        "ቴሌግራም ቻናል",
    "no-results":         "ምንም ምርት አልተገኘም። ሌላ ቃል ይሞክሩ።"
  }
};

// ──────────────────────────────────────
// App State
// ──────────────────────────────────────
let currentLang = "am";
let currentCategory = "all";
let searchQuery = "";

// ──────────────────────────────────────
// Init
// ──────────────────────────────────────
// ──────────────────────────────────────
// In-App Browser Detection & Browser Escape
// ──────────────────────────────────────
function isInAppBrowser() {
  const ua = navigator.userAgent || '';
  return /FBAN|FBAV|Instagram|musical_ly|BytedanceWebview|TikTok|LinkedInApp|Snapchat/i.test(ua);
}

function tryEscapeInAppBrowser() {
  if (!isInAppBrowser()) return;

  const ua = navigator.userAgent || '';
  const isAndroid = /Android/i.test(ua);
  const currentUrl = window.location.href;

  function showManualEscapeOverlay(url) {
    if (document.getElementById('iab-overlay')) return;
    const overlay = document.createElement('div');
    overlay.id = 'iab-overlay';
    overlay.style.cssText = `
      position: fixed; top: 0; left: 0; width: 100vw; height: 100vh;
      background-color: #ffffff; z-index: 100000; display: flex;
      flex-direction: column; align-items: center; justify-content: center;
      padding: 2rem; box-sizing: border-box; font-family: sans-serif; color: #111e3c;
    `;

    // Arrow indicator pointing to top-right corner where TikTok's menu (three dots ...) is located
    overlay.innerHTML = `
      <div style="position: absolute; top: 10px; right: 20px; font-size: 2.5rem; color: #1a73e8; animation: bounce 1.5s infinite;">↗</div>
      
      <div style="max-width: 420px; width: 100%; text-align: center; background: #f8fafc; padding: 2rem; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; max-height: 90vh; overflow-y: auto;">
        <h2 style="font-size: 1.3rem; margin-bottom: 0.5rem; font-weight: 700; color: #1e293b;">ሊንኩን ለመክፈት እነዚህን ደረጃዎች ይከተሉ</h2>
        <h3 style="font-size: 1.15rem; margin-bottom: 1rem; font-weight: 700; color: #475569; font-style: italic;">Follow the steps to access this link</h3>
        
        <p style="font-size: 0.85rem; color: #64748b; margin-bottom: 1.5rem; line-height: 1.4;">
          ይህ ገጽ ሙሉ በሙሉ እንዲሰራ በስልክዎ መደበኛ ማሰሻ መከፈት አለበት።<br>
          <span style="font-style: italic;">This link must be opened in your native browser to work correctly.</span>
        </p>
        
        <div style="text-align: left; margin-bottom: 1.5rem; font-size: 0.9rem; border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; padding: 1.2rem 0;">
          <!-- Step 1 -->
          <div style="display: flex; align-items: flex-start; margin-bottom: 1.2rem;">
            <span style="background: #1a73e8; color: white; width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 12px; font-weight: bold; font-size: 0.75rem; flex-shrink: 0; margin-top: 2px;">1</span>
            <div>
              <div style="font-weight: 600; color: #1e293b;">በላይኛው ቀኝ በኩል ያለውን <strong>•••</strong> ይጫኑ።</div>
              <div style="font-size: 0.8rem; color: #64748b; font-style: italic; margin-top: 2px;">Tap the <strong>•••</strong> icon at the top right.</div>
            </div>
          </div>
          
          <!-- Step 2 -->
          <div style="display: flex; align-items: flex-start;">
            <span style="background: #1a73e8; color: white; width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 12px; font-weight: bold; font-size: 0.75rem; flex-shrink: 0; margin-top: 2px;">2</span>
            <div>
              <div style="font-weight: 600; color: #1e293b;">በመቀጠል <strong>"Open in Browser"</strong> ወይም <strong>"Open in Safari"</strong> ይምረጡ።</div>
              <div style="font-size: 0.8rem; color: #64748b; font-style: italic; margin-top: 2px;">Choose <strong>"Open in Browser"</strong> or <strong>"Open in Safari"</strong>.</div>
            </div>
          </div>
        </div>

        <button id="iab-copy-btn" style="width: 100%; padding: 12px; background-color: #111e3c; color: white; border: none; border-radius: 8px; font-size: 0.95rem; font-weight: 600; cursor: pointer; transition: background 0.2s; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 2px;">
          <span>ሊንኩን ኮፒ ያድርጉ</span>
          <span style="font-size: 0.75rem; font-weight: normal; opacity: 0.85;">Copy link</span>
        </button>
        
        <button onclick="this.closest('#iab-overlay').remove()" style="margin-top: 1.2rem; background: none; border: none; color: #ef4444; font-size: 0.85rem; font-weight: 600; cursor: pointer; display: flex; flex-direction: column; align-items: center;">
          <span>በዚህ ይቆዩ</span>
          <span style="font-size: 0.75rem; font-weight: normal; opacity: 0.85; margin-top: 1px;">Stay here</span>
        </button>
      </div>

      <style>
        @keyframes bounce {
          0%, 100% { transform: translateY(0) translateX(0); }
          50% { transform: translateY(-8px) translateX(8px); }
        }
      </style>
    `;
    document.body.appendChild(overlay);

    // Setup Copy Link functionality
    const copyBtn = overlay.querySelector('#iab-copy-btn');
    if (copyBtn) {
      copyBtn.onclick = () => {
        navigator.clipboard.writeText(url).then(() => {
          copyBtn.textContent = 'ኮፒ ተደርጓል! (Copied!)';
          copyBtn.style.backgroundColor = '#10b981';
          setTimeout(() => {
            copyBtn.textContent = 'ሊንኩን ኮፒ ያድርጉ (Copy link)';
            copyBtn.style.backgroundColor = '#111e3c';
          }, 2000);
        }).catch(err => {
          console.error('Failed to copy link: ', err);
        });
      };
    }
  }

  if (isAndroid) {
    // Construct the destination URL without the protocol
    const cleanUrl = currentUrl.replace(/^https?:\/\//, '');
    
    // Construct the Android intent link targeting Chrome
    const intentUrl = `intent://${cleanUrl}#Intent;scheme=https;package=com.android.chrome;end`;
    
    // Attempt to redirect to the intent URL
    window.location.href = intentUrl;
    
    // If the intent redirect fails (e.g., Chrome not installed or intent blocked),
    // fallback to showing the manual instructions overlay.
    setTimeout(() => {
      if (!document.hidden) {
        showManualEscapeOverlay(currentUrl);
      }
    }, 1000);
  } else {
    // iOS (Safari): Apple enforces in-app WebKit, so code cannot force launch Safari.
    // Instead, display a premium full-screen walkthrough modal to guide the user.
    showManualEscapeOverlay(currentUrl);
  }
}

// Helper: open Telegram link, bypassing in-app browser via tg:// scheme
function openTelegramLink(tgSchemeUrl, httpsFallbackUrl) {
  // Use a hidden iframe to attempt the custom scheme.
  // This prevents Android webviews from showing an "Action can't be completed" toast
  // or ERR_UNKNOWN_URL_SCHEME page if the scheme isn't supported or app isn't installed.
  const iframe = document.createElement('iframe');
  iframe.style.display = 'none';
  document.body.appendChild(iframe);
  iframe.src = tgSchemeUrl;

  // If tg:// didn't navigate away (e.g. Telegram not installed), fall back to https://
  setTimeout(() => {
    document.body.removeChild(iframe);
    if (!document.hidden) {
      window.open(httpsFallbackUrl, '_blank');
    }
  }, 600);
}

document.addEventListener("DOMContentLoaded", () => {
  tryEscapeInAppBrowser();
  initScrollAnimations();
  const bar = document.querySelector(".sticky-cta-bar");
  if (bar) bar.style.transform = "translateY(100%)";
  window.addEventListener("scroll", handleScroll);
  initApp();
});

async function initApp() {
  // Show a subtle loading state on the product grid
  const grid = document.getElementById("productGrid");
  if (grid) {
    grid.innerHTML = `
      <div style="grid-column:1/-1;text-align:center;padding:3rem;opacity:0.6;">
        <div style="font-size:2rem;margin-bottom:0.5rem;">⏳</div>
        <p>Loading products…</p>
      </div>`;
  }

  try {
    // Use a relative URL (no leading slash) so it works on GitHub Pages
    // subdirectory URLs like /atlantic-trading-website/ as well as custom domains.
    const res = await fetch("products.json?v=" + new Date().getTime());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    products = await res.json();
  } catch (err) {
    console.warn("Could not fetch products.json, falling back to built-in data:", err);
    // Fallback to the _placeholder array seeded from the last known good data
    products = _placeholder;
  }

  renderCategories();
  renderFilterTabs();
  renderProducts();
  applyLanguage(currentLang);
}

// ──────────────────────────────────────
// Language
// ──────────────────────────────────────
function applyLanguage(lang) {
  currentLang = lang;
  const btn = document.getElementById("langToggleBtn");
  if (btn) {
    btn.innerHTML = lang === "en"
      ? `<span class="active-lang">EN</span><span class="divider">/</span><span class="inactive-lang">አማ</span>`
      : `<span class="inactive-lang">EN</span><span class="divider">/</span><span class="active-lang">አማ</span>`;
  }
  document.querySelectorAll("[data-key]").forEach(el => {
    const key = el.getAttribute("data-key");
    if (dictionary[lang][key]) el.textContent = dictionary[lang][key];
  });
  document.querySelectorAll("[data-key-placeholder]").forEach(el => {
    const key = el.getAttribute("data-key-placeholder");
    if (dictionary[lang][key]) el.setAttribute("placeholder", dictionary[lang][key]);
  });
  renderCategories();
  renderFilterTabs();
  renderProducts();
}

function toggleLanguage() {
  applyLanguage(currentLang === "en" ? "am" : "en");
}

// ──────────────────────────────────────
// Render Categories
// ──────────────────────────────────────
function renderCategories() {
  const container = document.getElementById("categoriesScroll");
  if (!container) return;
  container.innerHTML = "";
  categories.filter(c => c.id !== "all").forEach(cat => {
    const card = document.createElement("div");
    card.className = "category-card";
    card.onclick = () => selectCategory(cat.id);
    card.innerHTML = `
      <img src="${cat.image}" alt="${cat.name_en}" class="category-card-bg" loading="lazy">
      <div class="category-card-overlay">
        <h3 class="category-card-title">${currentLang === "en" ? cat.name_en : cat.name_am}</h3>
      </div>
    `;
    container.appendChild(card);
  });
}

// ──────────────────────────────────────
// Render Filter Tabs
// ──────────────────────────────────────
function renderFilterTabs() {
  const container = document.getElementById("filterTabs");
  if (!container) return;
  container.innerHTML = "";
  categories.forEach(cat => {
    const tab = document.createElement("button");
    tab.className = `filter-tab ${currentCategory === cat.id ? "active" : ""}`;
    tab.onclick = () => selectCategory(cat.id);
    tab.textContent = currentLang === "en" ? cat.name_en : cat.name_am;
    container.appendChild(tab);
  });
}

function selectCategory(categoryId) {
  currentCategory = categoryId;
  renderFilterTabs();
  renderProducts();
  document.getElementById("products")?.scrollIntoView({ behavior: "smooth" });
}

function handleSearch() {
  searchQuery = document.getElementById("searchInput").value.toLowerCase();
  renderProducts();
}

function resetFilters() {
  searchQuery = "";
  const searchInput = document.getElementById("searchInput");
  if (searchInput) searchInput.value = "";
  selectCategory('all');
}

// ──────────────────────────────────────
// Render Products
// ──────────────────────────────────────
function renderProducts() {
  const grid = document.getElementById("productGrid");
  if (!grid) return;
  grid.innerHTML = "";

  const filtered = products.filter(prod => {
    const matchCat    = currentCategory === "all" || prod.category === currentCategory;
    const matchSearch = prod.name_en.toLowerCase().includes(searchQuery)
                     || prod.name_am.includes(searchQuery)
                     || prod.description_en.toLowerCase().includes(searchQuery);
    return matchCat && matchSearch;
  });

  if (filtered.length === 0) {
    const empty = document.createElement("div");
    empty.className = "empty-state";
    empty.innerHTML = `
      <div class="empty-icon">🔍</div>
      <p>${dictionary[currentLang]["no-results"]}</p>
      <button onclick="resetFilters()" class="filter-tab active" style="margin-top:1rem;">
        ${currentLang === "en" ? "Show all products" : "ሁሉም ምርቶች ይታዩ"}
      </button>
    `;
    grid.appendChild(empty);
    return;
  }

  filtered.forEach((prod, idx) => {
    const card = document.createElement("div");
    card.className = "product-card";
    card.tabIndex = 0;
    card.setAttribute("role", "button");
    card.style.animationDelay = `${idx * 0.05}s`;
    
    card.onclick = () => openPDP(prod.id);
    card.onkeydown = (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        openPDP(prod.id);
      }
    };

    const name       = currentLang === "en" ? prod.name_en        : prod.name_am;
    const desc       = currentLang === "en" ? prod.description_en : prod.description_am;
    const fallbackPriceEn = "Contact for price";
    const fallbackPriceAm = "ያግኙን";
    const priceTextRaw = currentLang === "en" ? prod.price_display_en : (prod.price_display_am || prod.price_display_en);
    const priceText  = priceTextRaw || (currentLang === "en" ? fallbackPriceEn : fallbackPriceAm);
    const priceLabel = (prod.price_type === "tiered" && priceTextRaw) ? (currentLang === "en" ? "From" : "ከ") : "";
    const tag        = currentLang === "en" ? prod.tag_en         : prod.tag_am;

    card.innerHTML = `
      <div class="product-card-image-wrap">
        ${prod.tag_en ? `<div class="product-ribbon">${tag}</div>` : ""}
        <img src="${(prod.images && prod.images.length > 0) ? (typeof prod.images[0] === 'object' ? prod.images[0].image : prod.images[0]) : (prod.image_thumb || prod.image)}" alt="${name}" class="product-card-img" loading="lazy">
        <div class="product-card-overlay">
          <div class="product-card-details">
            <h3 class="product-card-title">${name}</h3>
            <p class="product-card-desc">${desc}</p>
            <div class="product-card-footer">
              <span class="product-card-price">${priceLabel ? priceLabel + ' ' : ''}${priceText}</span>
              <span class="product-card-action">View details</span>
            </div>
          </div>
        </div>
      </div>
    `;
    grid.appendChild(card);
  });
}

// ──────────────────────────────────────
// Product Detail Modal (PDP)
// ──────────────────────────────────────
function openPDP(productId) {
  const prod = products.find(p => p.id === productId);
  if (!prod) return;

  // ── Build swipeable image gallery ──────────────────────────
  // Collect all available images for this product.
  // Priority: prod.images array → fallback to image_full + image_thumb
  const gallery = document.getElementById("pdpGallery");
  const dotsEl  = document.getElementById("pdpGalleryDots");
  gallery.innerHTML = "";
  dotsEl.innerHTML  = "";

  const rawImages = prod.images && prod.images.length ? prod.images : [];
  const imgSrcs = rawImages.length
    ? rawImages.map(img => typeof img === 'object' ? img.image : img).filter(Boolean)
    : [prod.image_full || prod.image].filter(Boolean);

  const altText = currentLang === "en" ? prod.name_en : prod.name_am;

  // Configure navigation buttons
  const prevBtn = document.getElementById("pdpGalleryPrev");
  const nextBtn = document.getElementById("pdpGalleryNext");
  
  if (prevBtn && nextBtn) {
    if (imgSrcs.length > 1) {
      prevBtn.style.display = "flex";
      nextBtn.style.display = "flex";
      
      prevBtn.onclick = () => {
        const idx = Math.round(gallery.scrollLeft / gallery.offsetWidth);
        const newIdx = Math.max(0, idx - 1);
        gallery.scrollTo({ left: gallery.offsetWidth * newIdx, behavior: "smooth" });
      };
      
      nextBtn.onclick = () => {
        const idx = Math.round(gallery.scrollLeft / gallery.offsetWidth);
        const newIdx = Math.min(imgSrcs.length - 1, idx + 1);
        gallery.scrollTo({ left: gallery.offsetWidth * newIdx, behavior: "smooth" });
      };
    } else {
      prevBtn.style.display = "none";
      nextBtn.style.display = "none";
    }
  }

  imgSrcs.forEach((src, i) => {
    const img = document.createElement("img");
    img.src       = src;
    img.alt       = altText;
    img.className = "pdp-main-img";
    img.loading   = "lazy";
    gallery.appendChild(img);

    if (imgSrcs.length > 1) {
      const dot = document.createElement("span");
      dot.className = "pdp-gallery-dot" + (i === 0 ? " active" : "");
      dot.onclick = () => {
        gallery.scrollTo({ left: gallery.offsetWidth * i, behavior: "smooth" });
      };
      dotsEl.appendChild(dot);
    }
  });

  // Update dots on scroll
  gallery.onscroll = () => {
    const idx = Math.round(gallery.scrollLeft / gallery.offsetWidth);
    dotsEl.querySelectorAll(".pdp-gallery-dot").forEach((d, i) => {
      d.classList.toggle("active", i === idx);
    });
  };
  document.getElementById("pdpTagContainer").innerHTML = prod.tag_en
    ? `<span class="hero-badge-ribbon">${currentLang === "en" ? prod.tag_en : prod.tag_am}</span>` : "";
  document.getElementById("pdpTitle").textContent       = currentLang === "en" ? prod.name_en        : prod.name_am;
  
  const fallbackPriceEn = "Contact for price";
  const fallbackPriceAm = "ያግኙን";
  const pdpPriceTextRaw = currentLang === "en" ? prod.price_display_en : (prod.price_display_am || prod.price_display_en);
  const pdpPriceText = pdpPriceTextRaw || (currentLang === "en" ? fallbackPriceEn : fallbackPriceAm);
  const pdpPriceLabel = (prod.price_type === "tiered" && pdpPriceTextRaw) ? (currentLang === "en" ? "From " : "ከ ") : "";
  document.getElementById("pdpPrice").textContent       = pdpPriceLabel + pdpPriceText;
  
  document.getElementById("pdpDescription").textContent = currentLang === "en" ? prod.description_en : prod.description_am;

  const tiktokContainer = document.getElementById("pdpTiktokContainer");
  const tiktokBtn       = document.getElementById("pdpTiktokBtn");
  if (prod.tiktok_review && prod.tiktok_review.trim() !== "") {
    tiktokContainer.style.display = "block";
    tiktokBtn.href = prod.tiktok_review;
  } else {
    tiktokContainer.style.display = "none";
    tiktokBtn.href = "#";
  }

  const featuresList = document.getElementById("pdpFeaturesList");
  featuresList.innerHTML = "";
  (currentLang === "en" ? prod.features_en : prod.features_am).forEach(feat => {
    const li = document.createElement("li");
    li.textContent = feat;
    featuresList.appendChild(li);
  });

  const tiersContainer = document.getElementById("pdpTiersContainer");
  const tiersBody      = document.getElementById("pdpTiersBody");
  if (prod.price_type === "tiered" && prod.price_tiers) {
    tiersContainer.style.display = "block";
    tiersBody.innerHTML = "";
    prod.price_tiers.forEach(tier => {
      const row = document.createElement("tr");
      row.innerHTML = `<td><strong>${tier.size}</strong></td><td>${tier.price.toLocaleString()} ETB</td>`;
      tiersBody.appendChild(row);
    });
  } else {
    tiersContainer.style.display = "none";
  }

  // Build Telegram message — include product name, price, and a direct link to
  // the product image so the seller can immediately see what's being ordered.
  // Use document.baseURI to get the correct base path whether on GitHub Pages
  // subdirectory (/atlantic-trading-website/) or a future custom domain root.
  const baseUrl = document.baseURI.replace(/\/[^/]*$/, ""); // strip filename if any
  
  // Find the first image that is NOT a massive base64 data URL
  let imagePath = "";
  for (const src of imgSrcs) {
    if (src && !src.startsWith("data:")) {
      imagePath = src;
      break;
    }
  }
  
  let photoLabel = currentLang === "en" ? `Photo:` : `ፎቶ፡`;
  let photoLine = "";
  if (imagePath) {
    if (imagePath.startsWith("http")) {
      photoLine = `${photoLabel} ${imagePath}`;
    } else {
      photoLine = `${photoLabel} ${baseUrl}/${imagePath}`;
    }
  }

  // Strip emojis from the product name to prevent buggy in-app browsers 
  // from mangling URL-encoded emojis and causing 400 Bad Request errors.
  const rawNameEn = prod.name_en || prod.name_am || "";
  const rawNameAm = prod.name_am || prod.name_en || "";
  const cleanNameEn = rawNameEn.replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '').trim();
  const cleanNameAm = rawNameAm.replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '').trim();
  
  const cleanName = currentLang === "en" ? cleanNameEn : cleanNameAm;
  const priceDisplay = currentLang === "en" ? (prod.price_display_en || "") : (prod.price_display_am || prod.price_display_en || "");

  const greeting = currentLang === "en" ? `Hello Atlantic Trading! I'd like to order:` : `ሰላም አትላንቲክ ትሬዲንግ! ይህንን ማዘዝ እፈልጋለሁ፡`;
  const prodLabel = currentLang === "en" ? `Product:` : `ምርት፡`;
  const priceLabel = currentLang === "en" ? `Price:` : `ዋጋ፡`;
  const confirmSize = currentLang === "en" ? `(please confirm size)` : `(እባክዎ መጠኑን ያሳውቁ)`;
  const footerText = currentLang === "en" ? `Please let me know the next steps. Thank you!` : `እባክዎ ቀጣይ እርምጃዎችን ያሳውቁኝ። እናመሰግናለን!`;

  const msgArr = [
    greeting,
    ``,
    `${prodLabel} ${cleanName}`,
    prod.price_type === "flat"
      ? `${priceLabel} ${priceDisplay}`
      : `${priceLabel} ${priceDisplay} ${confirmSize}`
  ];
  
  if (photoLine) {
    msgArr.push(``, photoLine);
  }
  
  msgArr.push(``, footerText);
  const msg = msgArr.join("\n");
  const tgScheme = `tg://resolve?domain=Atlantictradingplc1&text=${encodeURIComponent(msg)}`;
  const tgHttps  = `https://t.me/Atlantictradingplc1?text=${encodeURIComponent(msg)}`;
  const ctaBtn = document.getElementById("pdpTelegramCta");
  // Set href as tg:// for direct Telegram app opening (bypasses in-app browser warning)
  ctaBtn.href = tgScheme;
  ctaBtn.onclick = function(e) {
    e.preventDefault();
    openTelegramLink(tgScheme, tgHttps);
  };

  document.getElementById("pdpModal").classList.add("active");
  document.body.style.overflow = "hidden";
}

function closePDP() {
  document.getElementById("pdpModal").classList.remove("active");
  document.body.style.overflow = "";
}

// Close with Escape key
document.addEventListener("keydown", e => { if (e.key === "Escape") closePDP(); });

// ──────────────────────────────────────
// Sticky CTA Bar
// ──────────────────────────────────────
function handleScroll() {
  const bar  = document.querySelector(".sticky-cta-bar");
  const hero = document.querySelector(".hero-section");
  const navBar = document.querySelector(".nav-bar");

  // Nav bar scroll effect
  if (navBar) {
    if (window.scrollY > 50) {
      navBar.classList.add("scrolled");
    } else {
      navBar.classList.remove("scrolled");
    }
  }

  // Sticky CTA bar
  if (!bar || !hero) return;
  const heroBottom = hero.offsetTop + hero.offsetHeight;
  bar.style.transform = window.scrollY > heroBottom - 60 ? "translateY(0)" : "translateY(100%)";
}

// ──────────────────────────────────────
// Scroll entrance animations
// ──────────────────────────────────────
function initScrollAnimations() {
  if (!("IntersectionObserver" in window)) return;
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add("visible");
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll(".section-header, .categories-section, .products-section").forEach(el => {
    el.classList.add("fade-in-up");
    observer.observe(el);
  });
}
